name: floor-heights
channels: [conda-forge]
dependencies:
  - python=3.12          # interpreter
  - gdal                 # pulls libgdal, proj, geos
  - proj-data
  - pdal
  - libpq                # psycopg wheels link against this
  # add cuda / cudnn here if you train on-GPU