name: floorheight
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  - pip
  # Formatting and Linters
  - black
  - mypy
  - pylint
  # Jupyter Notebooks
  - ipykernel
  - ipython
  # Utilities
  - click
  - tqdm
  # Spatial
  - fiona
  - geopandas # this will include gdal through conda-forge
  - shapely
  - rasterio
  # Data Science
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  # Google Street View
  - requests
  - pillow
  - pydantic
  - httpx
  # testing dependencies
  - pytest
  - pytest-cov
  - pytest-vcr
  - pytest-asyncio
  - isort
  - black
  - flake8
  - mypy
  - types-requests
  - types-Pillow
  - build
  - twine