# Floor Heights Pipeline Configuration

# Output folder for panoramas, clips and other data
output_root: "output"

# Regions in the project
regions: ["wagga","launceston", "tweed"]

# Sampling configuration
sampling:
  enabled: False       # Set to false to disable sampling
  sample_size: 100     # Fixed number of buildings to sample per region (if < total buildings)
  sample_fraction: 0.1 # Alternative: fraction of buildings to sample (0-1)
  random_seed: 42      # Seed for reproducible sampling