# Launceston data is also Zone 55 – EPSG 28355
crs: 28355

column_mappings:
  floor_level_m:  LCC_FLOOR       # (or NEXIS_FLOO – choose whichever is correct)
  ground_level_m: Survey_Grd
  property_type:  USE             # broad land-use / property category
  wall_material:  LOCAL_WALL
