PROPERTY_TYPE_MAP = {
    "C": "Commercial",
    "Com": "Commercial",
    "Commercial": "Commercial",
    "I": "Industrial",
    "Ind": "Industrial",
    "Industrial": "Industrial",
    "R": "Residential",
    "Res": "Residential",
    "Residential": "Residential",
    "E": "Education",
    "Edu": "Education",
    "Education": "Education",
    "EM": "Emergency",
    "Emer": "Emergency",
    "Emergency": "Emergency",
    "M": "Medical",
    "Med": "Medical",
    "Medical": "Medical",
    "W": "Worship",
    "Wor": "Worship",
    "Worship": "Worship",
    "Other": "Other",
}

WALL_MATERIAL_MAP = {
    "BK": "Brick",
    "BK - Brick": "Brick",
    "BKBD - Brick Board": "Brick",
    "BKR - Brick Rendered": "Brick",
    "BKV - Brick Veneer": "Brick",
    "BKVR - Brick Veneer Rendered": "Brick",
    "BRICK": "Brick",
    "Block": "Brick",
    "Brick": "Brick",
    "MBK - Masonry Brick": "Brick",
    "MBKR - Masonry Brick Rendered": "Brick",
    "MBKV - Masonry Brick Veneer": "Brick",
    "C - Concrete": "Concrete",
    "CB - Colorbond": "Colorbond",
    "CBKV - Concrete Brick Veneer": "Concrete",
    "CBL - Concrete Block": "Concrete",
    "CBLR - Concrete Block Rendered": "Concrete",
    "CLADDING": "Cladding",
    "CONCRETE": "Concrete",
    "CONR - Concrete Rendered": "Concrete",
    "CSHT - Cement Sheet": "Cement Sheet",
    "CSTR - Cement Sheet Rendered": "Cement Sheet",
    "CTP - Concrete Tilt Panel": "Concrete",
    "FC": "Fibre Cement",
    "FIBRO": "Fibre Cement",
    "Fibro": "Fibre Cement",
    "GI - Galvanised Iron": "Galvanised Iron",
    "Glass": "Glass",
    "IW - Imitation Weatherboard": "Weatherboard",
    "METC - Metal Cladding": "Metal",
    "Metal": "Metal",
    "OT": "Other",
    "OTHER": "Other",
    "Other": "Other",
    "PCP - Precast Concrete Panel": "Concrete",
    "Precast Concrete": "Concrete",
    "RENDER": "Rendered",
    "STON - Stone": "Stone",
    "Stone": "Stone",
    "TIMB - Timber": "Timber",
    "TIMBER": "Timber",
    "Timber": "Timber",
    "VB - Vertical Board": "Weatherboard",
    "WB": "Weatherboard",
    "WB - Weatherboard": "Weatherboard",
    "NO": None,
    "None": None,
    "YES": None,
}

ZONE_TO_PROPERTY_TYPE = {
    "General Residential": "Residential",
    "Inner Residential": "Residential",
    "Low Density Residential": "Residential",
    "Medium Density Residential": "Residential",
    "Environmental Living": "Residential",
    "Large Lot Residential": "Residential",
    "Village": "Residential",
    "Commercial": "Commercial",
    "Industrial": "Industrial",
    "Mixed Use": "Mixed Use",
    "Urban Mixed Use": "Mixed Use",
    "Rural Activity Zone": None,
    "Rural Landscape": None,
}

RESIDENTIAL_ZONES = {
    "General Residential",
    "Inner Residential",
    "Large Lot Residential",
    "Low Density Residential",
    "Medium Density Residential",
    "Environmental Living",
    "Village",
    "Rural Activity Zone",
    "Rural Landscape",
    "Mixed Use",
    "Urban Mixed Use",
}


def get_property_type_case_sql() -> str:
    cases = [f"WHEN \"{k}\" THEN '{v}'" for k, v in PROPERTY_TYPE_MAP.items() if v]
    return f"CASE {' '.join(cases)} ELSE NULL END"


def get_wall_material_case_sql() -> str:
    cases = [f"WHEN \"{k}\" THEN '{v}'" for k, v in WALL_MATERIAL_MAP.items() if v]
    return f"CASE {' '.join(cases)} ELSE NULL END"
