name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. System deps (Conda/Mamba)
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: floor-heights
          cache-environment: true
          cache-downloads: true

      # 3. Python deps (UV)
      - name: Install uv & wheel cache
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync Python deps
        run: |
          micromamba run -n floor-heights uv pip install --system -e .
          micromamba run -n floor-heights uv pip install --system pytest pytest-cov ruff mypy

      # 4. Linting and type checking
      - name: Lint with Ruff
        run: |
          micromamba run -n floor-heights uv run ruff check
          micromamba run -n floor-heights uv run ruff format --check

      - name: Type check with mypy
        run: |
          micromamba run -n floor-heights uv run mypy .

      # 5. Prune UV cache
      - run: micromamba run -n floor-heights uv cache prune --ci

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: floor-heights:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test image
        run: |
          docker run --rm --entrypoint="" floor-heights:test /app/.venv/bin/python -c "print('Docker image works!')"